In [1]:
!pip install feast scikit-learn pandas pyarrow

Collecting feast
  Downloading feast-0.65.0-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from feast) (26.1.0)
Requirement already satisfied: click<9.0.0,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from feast) (8.4.2)
Collecting colorama<1,>=0.3.9 (from feast)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: dill~=0.3.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.3.8)
Requirement already satisfied: protobuf>=4.24.0 in /usr/local/lib/python3.12/dist-packages (from feast) (5.29.6)
Requirement already satisfied: Jinja2<4,>=2 in /usr/local/lib/python3.12/dist-packages (from feast) (3.1.6)
Requirement already satisfied: mmh3 in /usr/local/lib/python3.12/dist-packages (from feast) (5.2.1)
Requirement already satisfied: numpy<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from feast) (2.0.2)
Requirement already satisfied: pydantic>=2.10.6 in /usr/local/lib/python3.12/dist-packages (from feast) (2.13.4)
Requirement already satisfied: pygments<3,>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from feast) (2.20.0)
Requirement already satisfied: PyYAML<7,>=5.4.0 in /usr/local/lib/python3.12/dist-packages (from feast) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from feast) (2.32.4)
Requirement already satisfied: SQLAlchemy>1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy[mypy]>1->feast) (2.0.51)
Requirement already satisfied: tabulate<1,>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.9.0)
Collecting tenacity<9,>=7 (from feast)
  Downloading tenacity-8.5.0-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: toml<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.10.2)
Requirement already satisfied: tqdm<5,>=4 in /usr/local/lib/python3.12/dist-packages (from feast) (4.67.3)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from feast) (4.5.2)
Requirement already satisfied: fastapi>=0.68.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.139.0)
Requirement already satisfied: starlette>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from feast) (1.3.1)
Collecting uvicorn<=0.34.0,>=0.30.6 (from uvicorn[standard]<=0.34.0,>=0.30.6->feast)
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Collecting uvicorn-worker (from feast)
  Downloading uvicorn_worker-0.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting gunicorn (from feast)
  Downloading gunicorn-26.0.0-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: dask>=2024.2.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]>=2024.2.1->feast) (2026.7.0)
Collecting prometheus_client<0.25.0,>=0.20.0 (from feast)
  Downloading prometheus_client-0.24.1-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from feast) (5.9.5)
Collecting bigtree>=0.19.2 (from feast)
  Downloading bigtree-1.5.3-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.12/dist-packages (from feast) (2.13.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (26.2)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (1.4.2)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (0.12.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.68.0->feast) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.68.0->feast) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.68.0->feast) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2<4,>=2->feast) (3.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.10.6->feast) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.10.6->feast) (2.46.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy>1->SQLAlchemy[mypy]>1->feast) (3.5.3)
Collecting mypy>=0.910 (from SQLAlchemy[mypy]>1->feast)
  Downloading mypy-2.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=1.0.1->feast) (4.14.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<=0.34.0,>=0.30.6->uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.16.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.8.0)
Requirement already satisfied: python-dotenv>=0.13 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (1.2.2)
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.22.1)
Requirement already satisfied: watchfiles>=0.13 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (1.2.0)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (15.0.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (2026.6.17)
INFO: pip is looking at multiple versions of uvicorn-worker to determine which version is compatible with other requirements. This could take a while.
Collecting uvicorn-worker (from feast)
  Downloading uvicorn_worker-0.3.0-py3-none-any.whl.metadata (2.6 kB)
Collecting mypy_extensions>=1.0.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting pathspec>=1.0.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading pathspec-1.1.1-py3-none-any.whl.metadata (14 kB)
Collecting librt>=0.13.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading librt-0.15.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.3 kB)
Collecting ast-serialize<1.0.0,>=0.6.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading ast_serialize-0.8.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (1.0.0)
Downloading feast-0.65.0-py3-none-any.whl (9.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 65.2 MB/s eta 0:00:00
Downloading bigtree-1.5.3-py3-none-any.whl (137 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 12.1 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading prometheus_client-0.24.1-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 5.2 MB/s eta 0:00:00
Downloading tenacity-8.5.0-py3-none-any.whl (28 kB)
Downloading uvicorn-0.34.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 5.7 MB/s eta 0:00:00
Downloading gunicorn-26.0.0-py3-none-any.whl (212 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 14.8 MB/s eta 0:00:00
Downloading uvicorn_worker-0.3.0-py3-none-any.whl (5.3 kB)
Downloading mypy-2.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (15.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 77.1 MB/s eta 0:00:00
Downloading ast_serialize-0.8.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 38.4 MB/s eta 0:00:00
Downloading librt-0.15.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (531 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 20.2 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading pathspec-1.1.1-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 3.9 MB/s eta 0:00:00
Installing collected packages: uvicorn, tenacity, prometheus_client, pathspec, mypy_extensions, librt, gunicorn, colorama, bigtree, ast-serialize, uvicorn-worker, mypy, feast
  Attempting uninstall: uvicorn
    Found existing installation: uvicorn 0.51.0
    Uninstalling uvicorn-0.51.0:
      Successfully uninstalled uvicorn-0.51.0
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.1.4
    Uninstalling tenacity-9.1.4:
      Successfully uninstalled tenacity-9.1.4
  Attempting uninstall: prometheus_client
    Found existing installation: prometheus_client 0.25.0
    Uninstalling prometheus_client-0.25.0:
      Successfully uninstalled prometheus_client-0.25.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.
Successfully installed ast-serialize-0.8.0 bigtree-1.5.3 colorama-0.4.6 feast-0.65.0 gunicorn-26.0.0 librt-0.15.0 mypy-2.3.0 mypy_extensions-1.1.0 pathspec-1.1.1 prometheus_client-0.24.1 tenacity-8.5.0 uvicorn-0.34.0 uvicorn-worker-0.3.0

In [2]:
import pandas as pd
df = pd.read_csv("/content/final_year_skill_gap_dataset_3000.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (3000, 22)

,Roll_No,Student_Name,Department,Year,Section,Gender,Programming_Language,Database_Skill,Cloud_Skill,Web_Technology,...,Coding_Score,Aptitude_Score,Communication_Score,Technical_Score,Projects_Completed,Certifications,Internships,Preferred_Career,Placement_Readiness_Score,Skill_Gap_Level
0,IT0001,Aadhya Reddy,IT,Final Year,D,Male,Python,MongoDB,Azure,Node.js,...,78,82,92,69,0,4,3,Software Developer,80,Low
1,CSE0002,Ishitha Rao,CSE,Final Year,D,Female,JavaScript,PostgreSQL,NaN,Node.js,...,52,86,90,35,1,5,3,Cloud Engineer,73,Medium
2,IT0003,Akhil Das,IT,Final Year,E,Female,Python,SQL Server,AWS,Django,...,51,86,37,81,3,4,0,Cyber Security Analyst,73,Medium
3,EEE0004,Meghana Naidu,EEE,Final Year,D,Female,Python,MySQL,Azure,Django,...,90,41,59,52,3,5,2,Data Analyst,83,Low
4,IT0005,Aditya Sharma,IT,Final Year,A,Female,JavaScript,PostgreSQL,Azure,Node.js,...,52,94,75,79,4,1,2,Business Analyst,85,Low

In [3]:
print("Columns:")
print(df.columns.tolist())

print("\nShape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

Columns:
['Roll_No', 'Student_Name', 'Department', 'Year', 'Section', 'Gender', 'Programming_Language', 'Database_Skill', 'Cloud_Skill', 'Web_Technology', 'Data_Tool', 'Soft_Skill_Strength', 'Coding_Score', 'Aptitude_Score', 'Communication_Score', 'Technical_Score', 'Projects_Completed', 'Certifications', 'Internships', 'Preferred_Career', 'Placement_Readiness_Score', 'Skill_Gap_Level']

Shape:
(3000, 22)

Missing Values:
Roll_No                        0
Student_Name                   0
Department                     0
Year                           0
Section                        0
Gender                         0
Programming_Language           0
Database_Skill                 0
Cloud_Skill                  763
Web_Technology                 0
Data_Tool                      0
Soft_Skill_Strength            0
Coding_Score                   0
Aptitude_Score                 0
Communication_Score            0
Technical_Score                0
Projects_Completed             0
Certifications                 0
Internships                    0
Preferred_Career               0
Placement_Readiness_Score      0
Skill_Gap_Level                0
dtype: int64

In [4]:
# Feature Engineering for Skill Gap Dataset

# 1. Average of core technical skills
df["technical_average"] = (
    df["Coding_Score"]
    + df["Aptitude_Score"]
    + df["Communication_Score"]
    + df["Technical_Score"]
) / 4

# 2. Experience-related score
df["experience_score"] = (
    df["Projects_Completed"]
    + df["Certifications"]
    + df["Internships"]
)

# 3. Overall skill strength
df["skill_strength_score"] = (
    df["technical_average"] * 0.7
    + df["experience_score"] * 2
)

# 4. Keep the score within 0-100
df["skill_strength_score"] = df["skill_strength_score"].clip(0, 100)

# Display the new features
df[
    [
        "Roll_No",
        "Coding_Score",
        "Aptitude_Score",
        "Communication_Score",
        "Technical_Score",
        "Projects_Completed",
        "Certifications",
        "Internships",
        "technical_average",
        "experience_score",
        "skill_strength_score",
        "Skill_Gap_Level"
    ]
].head(10)

,Roll_No,Coding_Score,Aptitude_Score,Communication_Score,Technical_Score,Projects_Completed,Certifications,Internships,technical_average,experience_score,skill_strength_score,Skill_Gap_Level
0,IT0001,78,82,92,69,0,4,3,80.25,7,70.175,Low
1,CSE0002,52,86,90,35,1,5,3,65.75,9,64.025,Medium
2,IT0003,51,86,37,81,3,4,0,63.75,7,58.625,Medium
3,EEE0004,90,41,59,52,3,5,2,60.50,10,62.350,Low
4,IT0005,52,94,75,79,4,1,2,75.00,7,66.500,Low
5,AIDS0006,76,66,60,91,5,3,1,73.25,9,69.275,Low
6,AIDS0007,83,38,90,42,1,5,1,63.25,7,58.275,Medium
7,AIDS0008,78,91,69,83,2,6,2,80.25,10,76.175,Low
8,CSE0009,88,75,67,73,1,1,2,75.75,4,61.025,Low
9,AIML0010,50,91,71,95,0,0,3,76.75,3,59.725,Medium

In [5]:
print("New Dataset Shape:", df.shape)

print("\nNew Columns:")
print(df.columns.tolist())

New Dataset Shape: (3000, 25)

New Columns:
['Roll_No', 'Student_Name', 'Department', 'Year', 'Section', 'Gender', 'Programming_Language', 'Database_Skill', 'Cloud_Skill', 'Web_Technology', 'Data_Tool', 'Soft_Skill_Strength', 'Coding_Score', 'Aptitude_Score', 'Communication_Score', 'Technical_Score', 'Projects_Completed', 'Certifications', 'Internships', 'Preferred_Career', 'Placement_Readiness_Score', 'Skill_Gap_Level', 'technical_average', 'experience_score', 'skill_strength_score']

In [6]:
# Prepare dataset for Feast

import pandas as pd

# Create a unique entity ID for each student
df["student_id"] = df["Roll_No"].astype(str)

# Create an event timestamp required by Feast
df["event_timestamp"] = pd.Timestamp("2026-01-01")

# Select features that will be stored in Feast
feature_df = df[
    [
        "student_id",
        "event_timestamp",
        "Coding_Score",
        "Aptitude_Score",
        "Communication_Score",
        "Technical_Score",
        "Projects_Completed",
        "Certifications",
        "Internships",
        "Placement_Readiness_Score",
        "technical_average",
        "experience_score",
        "skill_strength_score"
    ]
].copy()

# Save as Parquet offline data
feature_df.to_parquet(
    "/content/skill_gap_features.parquet",
    index=False
)

print("Feature dataset shape:", feature_df.shape)
print("\nParquet file created successfully!")
print("/content/skill_gap_features.parquet")

feature_df.head()

Feature dataset shape: (3000, 13)

Parquet file created successfully!
/content/skill_gap_features.parquet

,student_id,event_timestamp,Coding_Score,Aptitude_Score,Communication_Score,Technical_Score,Projects_Completed,Certifications,Internships,Placement_Readiness_Score,technical_average,experience_score,skill_strength_score
0,IT0001,2026-01-01,78,82,92,69,0,4,3,80,80.25,7,70.175
1,CSE0002,2026-01-01,52,86,90,35,1,5,3,73,65.75,9,64.025
2,IT0003,2026-01-01,51,86,37,81,3,4,0,73,63.75,7,58.625
3,EEE0004,2026-01-01,90,41,59,52,3,5,2,83,60.50,10,62.350
4,IT0005,2026-01-01,52,94,75,79,4,1,2,85,75.00,7,66.500

In [7]:
import os

print("File exists:", os.path.exists("/content/skill_gap_features.parquet"))
print("File size:", os.path.getsize("/content/skill_gap_features.parquet"), "bytes")

File exists: True
File size: 58017 bytes

In [8]:
import os

os.makedirs("/content/feast_skillgap/feature_repo/data", exist_ok=True)

# Copy the Parquet file into the Feast project
import shutil

shutil.copy(
    "/content/skill_gap_features.parquet",
    "/content/feast_skillgap/feature_repo/data/skill_gap_features.parquet"
)

print("Feast project folder created successfully!")

Feast project folder created successfully!

In [9]:
%cd /content/feast_skillgap

!feast init feature_repo

/content/feast_skillgap
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'

Creating a new Feast repository in /content/feast_skillgap/feature_repo.

In [10]:
%cd /content/feast_skillgap/feature_repo

!cat feature_store.yaml

/content/feast_skillgap/feature_repo
cat: feature_store.yaml: No such file or directory

In [11]:
%%writefile /content/feast_skillgap/feature_repo/feature_store.yaml

project: skill_gap
provider: local
registry: data/registry.db
online_store:
    path: data/online_store.db
offline_store:
    type: file
entity_key_serialization_version: 3

Writing /content/feast_skillgap/feature_repo/feature_store.yaml

In [12]:
%cd /content/feast_skillgap/feature_repo

!ls -la

/content/feast_skillgap/feature_repo
total 28
drwxr-xr-x 4 root root 4096 Aug 12 06:05 .
drwxr-xr-x 3 root root 4096 Aug 12 06:01 ..
drwxr-xr-x 2 root root 4096 Aug 12 06:01 data
drwxr-xr-x 4 root root 4096 Aug 12 06:03 feature_repo
-rw-r--r-- 1 root root  174 Aug 12 06:05 feature_store.yaml
-rw-r--r-- 1 root root  463 Aug 12 05:42 .gitignore
-rw-r--r-- 1 root root    0 Aug 12 05:42 __init__.py
-rw-r--r-- 1 root root 2523 Aug 12 05:42 README.md

In [13]:
!ls -lh /content/feast_skillgap/feature_repo/data

total 60K
-rw-r--r-- 1 root root 57K Aug 12 06:01 skill_gap_features.parquet

In [14]:
%%writefile /content/feast_skillgap/feature_repo/features.py

from datetime import timedelta

from feast import Entity, FeatureView, Field
from feast.types import Float32, Int64
from feast.infra.offline_stores.file_source import FileSource


# Entity
student = Entity(
    name="student_id",
    join_keys=["student_id"],
    description="Unique identifier for each final-year student"
)


# Offline data source
skill_gap_source = FileSource(
    path="/content/feast_skillgap/feature_repo/data/skill_gap_features.parquet",
    timestamp_field="event_timestamp"
)


# Feature View
skill_gap_features = FeatureView(
    name="student_skill_gap_features",
    entities=[student],
    ttl=timedelta(days=365),
    schema=[
        Field(name="Coding_Score", dtype=Float32),
        Field(name="Aptitude_Score", dtype=Float32),
        Field(name="Communication_Score", dtype=Float32),
        Field(name="Technical_Score", dtype=Float32),
        Field(name="Projects_Completed", dtype=Int64),
        Field(name="Certifications", dtype=Int64),
        Field(name="Internships", dtype=Int64),
        Field(name="Placement_Readiness_Score", dtype=Float32),
        Field(name="technical_average", dtype=Float32),
        Field(name="experience_score", dtype=Float32),
        Field(name="skill_strength_score", dtype=Float32),
    ],
    source=skill_gap_source,
)

Writing /content/feast_skillgap/feature_repo/features.py

In [15]:
!cat /content/feast_skillgap/feature_repo/features.py

from datetime import timedelta

from feast import Entity, FeatureView, Field
from feast.types import Float32, Int64
from feast.infra.offline_stores.file_source import FileSource


# Entity
student = Entity(
    name="student_id",
    join_keys=["student_id"],
    description="Unique identifier for each final-year student"
)


# Offline data source
skill_gap_source = FileSource(
    path="/content/feast_skillgap/feature_repo/data/skill_gap_features.parquet",
    timestamp_field="event_timestamp"
)


# Feature View
skill_gap_features = FeatureView(
    name="student_skill_gap_features",
    entities=[student],
    ttl=timedelta(days=365),
    schema=[
        Field(name="Coding_Score", dtype=Float32),
        Field(name="Aptitude_Score", dtype=Float32),
        Field(name="Communication_Score", dtype=Float32),
        Field(name="Technical_Score", dtype=Float32),
        Field(name="Projects_Completed", dtype=Int64),
        Field(name="Certifications", dtype=Int64),
        Field(name="Internships", dtype=Int64),
        Field(name="Placement_Readiness_Score", dtype=Float32),
        Field(name="technical_average", dtype=Float32),
        Field(name="experience_score", dtype=Float32),
        Field(name="skill_strength_score", dtype=Float32),
    ],
    source=skill_gap_source,
)

In [16]:
%cd /content/feast_skillgap/feature_repo

!feast apply

/content/feast_skillgap/feature_repo
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/feast_skillgap/feature_repo/feature_repo/feature_definitions.py:29: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'driver'.
  driver = Entity(name="driver", join_keys=["driver_id"])
/content/feast_skillgap/feature_repo/features.py:10: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'student_id'.
  student = Entity(
Project object name should match with the project name defined in feature_store.yaml

In [17]:
import os
import shutil

old_folder = "/content/feast_skillgap/feature_repo/feature_repo"

if os.path.exists(old_folder):
    shutil.rmtree(old_folder)
    print("Old default Feast files removed successfully!")
else:
    print("Old folder not found.")

Old default Feast files removed successfully!

In [18]:
%%writefile /content/feast_skillgap/feature_repo/feature_store.yaml

project: skill_gap
provider: local
registry: data/registry.db

online_store:
    path: data/online_store.db

offline_store:
    type: file

entity_key_serialization_version: 3

Overwriting /content/feast_skillgap/feature_repo/feature_store.yaml

In [19]:
!cat /content/feast_skillgap/feature_repo/feature_store.yaml

project: skill_gap
provider: local
registry: data/registry.db

online_store:
    path: data/online_store.db

offline_store:
    type: file

entity_key_serialization_version: 3

In [20]:
%cd /content/feast_skillgap/feature_repo

!feast apply

/content/feast_skillgap/feature_repo
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/feast_skillgap/feature_repo/features.py:10: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'student_id'.
  student = Entity(
No project found in the repository. Using project name skill_gap defined in feature_store.yaml
Applying changes for project skill_gap
Created project skill_gap
Created entity student_id
Created feature view student_skill_gap_features

Created sqlite table skill_gap_student_skill_gap_features

In [21]:
from feast import FeatureStore
import pandas as pd

# Connect to Feast feature store
store = FeatureStore(
    repo_path="/content/feast_skillgap/feature_repo"
)

# Create entity dataframe for historical retrieval
entity_df = df[
    [
        "student_id",
        "event_timestamp"
    ]
].copy()

# Retrieve historical features
historical_features = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "student_skill_gap_features:Coding_Score",
        "student_skill_gap_features:Aptitude_Score",
        "student_skill_gap_features:Communication_Score",
        "student_skill_gap_features:Technical_Score",
        "student_skill_gap_features:Projects_Completed",
        "student_skill_gap_features:Certifications",
        "student_skill_gap_features:Internships",
        "student_skill_gap_features:Placement_Readiness_Score",
        "student_skill_gap_features:technical_average",
        "student_skill_gap_features:experience_score",
        "student_skill_gap_features:skill_strength_score",
    ],
).to_df()

print("Historical Feature Shape:", historical_features.shape)

historical_features.head(10)

Historical Feature Shape: (3000, 13)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,event_timestamp,Coding_Score,Aptitude_Score,Communication_Score,Technical_Score,Projects_Completed,Certifications,Internships,Placement_Readiness_Score,technical_average,experience_score,skill_strength_score
0,IT0001,2026-01-01 00:00:00+00:00,78,82,92,69,0,4,3,80,80.25,7,70.175
1,ECE1995,2026-01-01 00:00:00+00:00,52,63,54,59,0,2,1,52,57.00,3,45.900
2,MECH1996,2026-01-01 00:00:00+00:00,64,46,66,56,4,0,2,73,58.00,6,52.600
3,AIML1997,2026-01-01 00:00:00+00:00,64,95,65,56,2,2,2,74,70.00,6,61.000
4,EEE1998,2026-01-01 00:00:00+00:00,79,48,61,91,0,5,2,74,69.75,7,62.825
5,IT1999,2026-01-01 00:00:00+00:00,73,36,42,44,2,6,2,70,48.75,10,54.125
6,CIVIL2000,2026-01-01 00:00:00+00:00,86,60,43,80,1,5,1,75,67.25,7,61.075
7,CIVIL2001,2026-01-01 00:00:00+00:00,59,37,43,80,1,3,2,63,54.75,6,50.325
8,ECE2002,2026-01-01 00:00:00+00:00,64,90,90,57,3,1,0,75,75.25,4,60.675
9,CSE2003,2026-01-01 00:00:00+00:00,83,86,38,92,3,3,0,83,74.75,6,64.325

In [22]:
print("Missing values in historical features:")
print(historical_features.isnull().sum())

Missing values in historical features:
student_id                   0
event_timestamp              0
Coding_Score                 0
Aptitude_Score               0
Communication_Score          0
Technical_Score              0
Projects_Completed           0
Certifications               0
Internships                  0
Placement_Readiness_Score    0
technical_average            0
experience_score             0
skill_strength_score         0
dtype: int64

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Feast historical features
X = historical_features.drop(
    columns=["student_id", "event_timestamp"]
)

# Target from original dataset
y = df["Skill_Gap_Level"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Create ML model
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Model Accuracy: 47.33 %

Classification Report:
              precision    recall  f1-score   support

        High       0.00      0.00      0.00        28
         Low       0.51      0.64      0.57       315
      Medium       0.41      0.32      0.36       257

    accuracy                           0.47       600
   macro avg       0.30      0.32      0.31       600
weighted avg       0.44      0.47      0.45       600

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [24]:
print("Skill Gap Level Distribution:")
print(y.value_counts())

print("\nPercentage:")
print(y.value_counts(normalize=True) * 100)

Skill Gap Level Distribution:
Skill_Gap_Level
Low       1573
Medium    1284
High       143
Name: count, dtype: int64

Percentage:
Skill_Gap_Level
Low       52.433333
Medium    42.800000
High       4.766667
Name: proportion, dtype: float64

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Feast historical features
X = historical_features.drop(
    columns=["student_id", "event_timestamp"]
)

# Target
y = df["Skill_Gap_Level"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Balanced Random Forest
balanced_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

# Train
balanced_model.fit(X_train, y_train)

# Prediction
y_pred_balanced = balanced_model.predict(X_test)

# Accuracy
balanced_accuracy = accuracy_score(y_test, y_pred_balanced)

print("Balanced Random Forest Accuracy:",
      round(balanced_accuracy * 100, 2), "%")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_balanced,
        zero_division=0
    )
)

Balanced Random Forest Accuracy: 48.33 %

Classification Report:
              precision    recall  f1-score   support

        High       0.00      0.00      0.00        28
         Low       0.51      0.68      0.59       315
      Medium       0.41      0.30      0.34       257

    accuracy                           0.48       600
   macro avg       0.31      0.33      0.31       600
weighted avg       0.45      0.48      0.46       600

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [26]:
# Save the final trained model

import joblib

final_model = balanced_model

joblib.dump(
    final_model,
    "/content/feast_skillgap/skill_gap_model.pkl"
)

print("Final model saved successfully!")
print("Model accuracy:", round(balanced_accuracy * 100, 2), "%")

Final model saved successfully!
Model accuracy: 48.33 %

In [27]:
%cd /content/feast_skillgap/feature_repo

!feast materialize 2026-01-01T00:00:00 2026-12-31T23:59:59

/content/feast_skillgap/feature_repo
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
Materializing 1 feature views from 2026-01-01 00:00:00+00:00 to 2026-12-31 23:59:59+00:00 into the sqlite online store.

student_skill_gap_features:

In [28]:
from feast import FeatureStore

# Connect to Feast
store = FeatureStore(
    repo_path="/content/feast_skillgap/feature_repo"
)

# Retrieve online features for one student
online_features = store.get_online_features(
    features=[
        "student_skill_gap_features:Coding_Score",
        "student_skill_gap_features:Aptitude_Score",
        "student_skill_gap_features:Communication_Score",
        "student_skill_gap_features:Technical_Score",
        "student_skill_gap_features:Projects_Completed",
        "student_skill_gap_features:Certifications",
        "student_skill_gap_features:Internships",
        "student_skill_gap_features:Placement_Readiness_Score",
        "student_skill_gap_features:technical_average",
        "student_skill_gap_features:experience_score",
        "student_skill_gap_features:skill_strength_score",
    ],
    entity_rows=[
        {"student_id": "IT0001"}
    ]
).to_dict()

print("Online Feature Output:")
print(online_features)

Online Feature Output:
{'student_id': ['IT0001'], 'Internships': [3], 'Certifications': [4], 'Technical_Score': [69.0], 'Placement_Readiness_Score': [80.0], 'Coding_Score': [78.0], 'technical_average': [80.25], 'Projects_Completed': [0], 'experience_score': [7.0], 'Communication_Score': [92.0], 'Aptitude_Score': [82.0], 'skill_strength_score': [70.17500305175781]}

In [30]:
import pandas as pd
import joblib

# Load final model
final_model = joblib.load(
    "/content/feast_skillgap/skill_gap_model.pkl"
)

# Convert Feast online features to DataFrame
online_df = pd.DataFrame(online_features)

# Get the exact feature order used during model training
expected_features = final_model.feature_names_in_

print("Expected feature order:")
print(list(expected_features))

# Reorder online features exactly as training order
X_online = online_df[list(expected_features)]

# Make final prediction
prediction = final_model.predict(X_online)

print("\nStudent ID:", online_df["student_id"].iloc[0])
print("Predicted Skill Gap Level:", prediction[0])

Expected feature order:
['Coding_Score', 'Aptitude_Score', 'Communication_Score', 'Technical_Score', 'Projects_Completed', 'Certifications', 'Internships', 'Placement_Readiness_Score', 'technical_average', 'experience_score', 'skill_strength_score']

Student ID: IT0001
Predicted Skill Gap Level: Low

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [31]:
from google.colab import files

files.download("/content/final_year_skill_gap_dataset_3000.csv")

In [32]:
from google.colab import files

files.download("/content/feast_skillgap/skill_gap_model.pkl")

In [33]:
from google.colab import files

files.download("/content/Skill_Gap_Analysis_with_Feast.ipynb")

FileNotFoundError: Cannot find file: /content/Skill_Gap_Analysis_with_Feast.ipynb

In [34]:
import os

print(os.listdir("/content"))

['.config', 'final_year_skill_gap_dataset_3000.csv', 'feast_skillgap', 'skill_gap_features.parquet', 'sample_data']